### PR TITLE
Fix/revoke authorization

### LINKED ISSUE #406: A provider might needs an authorization header in the revoke endpoint
## Issue

As described in [rfc7009#section-2.1](https://tools.ietf.org/html/rfc7009#section-2.1) the client can also includes its authentication credentials in the request

---

## Environment

* **Your Identity Provider**: `Custom provider`
* **Platform that you're experiencing the issue on**: `both`
* **Are you using Expo?**: `No`

### PR DESCRIPTION
**Pull request by ehapmgs**
Fixes #406 
Fixes https://github.com/FormidableLabs/react-native-app-auth/pull/291

## Description

adding an authorization header for the revoke endpoint where some provider might need it

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -167,8 +168,8 @@ export const refresh = (
 };
 
 export const revoke = async (
-  { clientId, issuer, serviceConfiguration },
-  { tokenToRevoke, sendClientId = false }
+  { clientId, issuer, serviceConfiguration, clientSecret },
+  { tokenToRevoke, sendClientId = false, includeBasicAuthorization = false }
```
Comment (kadikraman) [inline index.js]: `includeBasicAuthorization` should also be added to `RevokeConfiguration` in `index.d.ts`

File: index.js [hunk 2]
```diff
@@ -199,6 +203,7 @@ export const revoke = async (
     method: 'POST',
     headers: {
       'Content-Type': 'application/x-www-form-urlencoded',
+      Authorization: `${includeBasicAuthorization ? `basic ${basicAuth}` : ''}`,
```
Comment (kadikraman) [inline index.js]: I'd prefer creating headers as a constant above and adding the auth header optionally:
```
const headers = {
  'Content-Type': 'application/x-www-form-urlencoded',
};

if (includeBasicAuthorization) {
  headers.Authorization =`basic ${base64.encode(`${clientId}:${clientSecret}`)}`,
}
```

This way you only have one conditional statement and it's a bit easier to follow

Comment (ehapmgs) [reply index.js]: done

File: index.js (hunk 1 above)
Comment (ehapmgs) [reply index.js]: please check a22518e9c1044b6522d0ccf8d0ceba4eee4d2884

File: index.js (hunk 2 above)
Comment (kadikraman) [reply index.js]: Thank you! I've just been thinking about this PR, and would really like to avoid adding a dependency if possible (I'm planning on getting rid of `invariant` as well).

What do you think about instead of `includeBasicAuthorization`, we could pass in a `customHeaders` param (we already do something similar for the `authorize` call). This way, the logic for the base 64 encoding would live in the app code, rather than the library 🤔

Comment (ehapmgs) [reply index.js]: I had a similar idea at first but I thought we could make simpler for the app code since we already have clientId & clientSecret in the config (I guess the native library is doing the same), but the down side of it we would add an extra dependency.

let me know what you think I will be happy to create a new pull request for your approach.

Comment (kadikraman) [reply index.js]: Alright, let's just leave it as 👍

**Comment by kadikraman** [comment]
Released in [v5.0.0](https://github.com/FormidableLabs/react-native-app-auth/releases/tag/v5.0.0) 🎉
